# Generated by Django 4.1.2 on 2022-10-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_category_slug_alter_newsletter_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
