# Generated by Django 4.1.2 on 2022-11-14 19:04

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_author_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_crop",
            field=image_cropping.fields.ImageRatioField(
                "main_image",
                "110x110",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="image crop",
            ),
        ),
    ]
