# Generated by Django 4.1.2 on 2022-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_remove_article_image_crop_article_main_image_crop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="main_image_crop",
            field=models.ImageField(upload_to="images/crop/"),
        ),
    ]
