# Generated by Django 4.1.2 on 2022-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_comment_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_moderated",
            field=models.BooleanField(default=False),
        ),
    ]
