# Generated by Django 4.1.2 on 2022-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_comment_is_moderated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField()),
                ("subject", models.CharField(max_length=50)),
            ],
        ),
    ]
